import { cn } from '@/lib/utils';
import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';

import '../styles/globals.css';

const roboto = Roboto({
    variable: '--font-roboto',
    subsets: ['latin', 'cyrillic'],
});

export const metadata: Metadata = {
    title: 'ЗНО/НМТ з англійської мови',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={cn(
                    'desk:bg-[url(../public/background/background-2x.jpg)] bg-[url(../public/background/background.jpg)] bg-cover bg-fixed bg-left bg-no-repeat font-sans antialiased',
                    roboto.variable,
                )}
            >
                {children}
            </body>
        </html>
    );
}
