import { RouteBasesMain } from '@/lib/constants/routeBases';
import { TestSessionLabels } from '@/lib/constants/testSessions';
import { TestTypeLabels } from '@/lib/constants/tests';
import getTestTypeLabelByTestId from '@/lib/helpers/test/getTestTypeLabelByTestId';
import parseTestIdString from '@/lib/helpers/test/parseTestIdString';
import { TestTypeData } from '@/lib/types/test';
import { TestSession, TestSessionId } from '@/lib/types/testSession';

import { TaskConfig } from './task.types';

class Task {
    private readonly _testId: string;
    private readonly _testSession: TestSessionId;

    private readonly _taskId: string;
    private readonly _taskNumber: number;

    private readonly _questionNumbers: number[];
    private readonly _answerLetters: string[];

    constructor({
        testId,
        testSession,
        taskId,
        taskNumber,
        questionNumbers,
        answerLetters,
    }: TaskConfig) {
        this._testId = testId;
        this._testSession = testSession;
        this._taskId = taskId;
        this._taskNumber = taskNumber;
        this._questionNumbers = questionNumbers;
        this._answerLetters = answerLetters;
    }

    // -------------- TEST -----------------

    /**
     * Returns id of the whole test (e.g. 'zno_2011', 'nmt_2023')
     */
    public getTestId = (): string => {
        return this._testId;
    };

    /**
     * Returns the test session data - id (e.g. 'demo', 'main', 'extra')
     * and label (e.g. 'Пробна сесія', 'Основна сесія', 'Додаткова сесія').
     */
    public getTestSession = (): TestSession => {
        return {
            id: this._testSession,
            label: TestSessionLabels[this._testSession],
        };
    };

    /**
     * Returns the test type data - type (e.g. 'zno', 'nmt') and label (e.g. 'ЗНО', 'НМТ'),
     * or null if the test ID is invalid.
     */
    public getTestType = (): TestTypeData | null => {
        const testData = parseTestIdString(this._testId);

        if (!testData) {
            return null;
        }

        return {
            testType: testData.testType,
            testTypeLabel: TestTypeLabels[testData.testType],
        };
    };

    /**
     * Returns the test year (e.g. '2011', '2023'), or null if the test ID is invalid.
     */
    public getTestYear = (): string | null => {
        const testData = parseTestIdString(this._testId);

        if (!testData) {
            return null;
        }

        return testData.testYear;
    };

    /**
     * Returns the test label (e.g. 'ЗНО 2011', 'НМТ 2023'),
     * or null if the test ID is invalid.
     */
    public getTestLabel = (): string | null => {
        return getTestTypeLabelByTestId(this._testId);
    };

    // -------------- TASK -----------------

    /**
     * Returns id of the current task (randomly generated by the server)
     */
    public getTaskId = (): string => {
        return this._taskId;
    };

    /**
     * Returns the task number - always as counted in ZNO test (not NMT) (e.g. 4, 5, 6)
     */
    public getTaskNumber = (): number => {
        return this._taskNumber;
    };

    /**
     * Returns the actual task number:
     * If test type is 'zno' - counted as 4, 5, 6.
     * If test type is 'nmt' - counted as 1, 2, 3.
     */
    private _getActualTaskNumber = (): number => {
        const testType = this.getTestType()?.testType;

        if (!testType) {
            return this._taskNumber;
        }

        return testType === RouteBasesMain.zno
            ? this._taskNumber
            : this._taskNumber - 3;
    };

    /**
     * Returns the task title (e.g. 'Task 4')
     */
    public getTaskTitle = (): string => {
        return `Task ${this._getActualTaskNumber()}`;
    };

    /**
     * Returns the task label (e.g. 'Завдання 4/1',
     * where 4 means task number as counted in ZNO test and 1 as counted in NMT test)
     */
    public getTaskLabel = (): string => {
        return `Завдання ${this._taskNumber}/${this._taskNumber - 3}`;
    };
}

export default Task;
