import { TestSessionLabels } from '@/lib/constants/testSessions';
import { TestTypeLabels } from '@/lib/constants/tests';
import parseTestIdString from '@/lib/helpers/test/parseTestIdString';
import { TestTypeData } from '@/lib/types/test';
import { TestSession, TestSessionId } from '@/lib/types/testSession';

import { TaskConfig } from './task.types';

class Task {
    private readonly _testId: string;
    private readonly _testSession: TestSessionId;

    private readonly _taskId: string;
    private readonly _taskNumber: number;

    private readonly _questionNumbers: number[];
    private readonly _answerLetters: string[];

    constructor({
        testId,
        testSession,
        taskId,
        taskNumber,
        questionNumbers,
        answerLetters,
    }: TaskConfig) {
        this._testId = testId;
        this._testSession = testSession;
        this._taskId = taskId;
        this._taskNumber = taskNumber;
        this._questionNumbers = questionNumbers;
        this._answerLetters = answerLetters;
    }

    /**
     * Returns id of the whole test (e.g. 'zno_2011', 'nmt_2023')
     */
    public getTestId = (): string => {
        return this._testId;
    };

    /**
     * Returns the test session data - id (e.g. 'demo', 'main', 'extra')
     * and label (e.g. 'Пробна сесія', 'Основна сесія', 'Додаткова сесія').
     */
    public getTestSession = (): TestSession => {
        return {
            id: this._testSession,
            label: TestSessionLabels[this._testSession],
        };
    };

    /**
     * Returns the test type data - type (e.g. 'zno', 'nmt') and label (e.g. 'ЗНО', 'НМТ'),
     * or null if the test ID is invalid.
     */
    public getTestType = (): TestTypeData | null => {
        const testData = parseTestIdString(this._testId);

        if (!testData) {
            return null;
        }

        return {
            testType: testData.testType,
            testTypeLabel: TestTypeLabels[testData.testType],
        };
    };

    /**
     * Returns id of the current task (randomly generated by the server)
     */
    public getTaskId = (): string => {
        return this._taskId;
    };

    /**
     * Returns the task number - always as counted in ZNO test (not NMT) (e.g. 4, 5, 6)
     */
    public getTaskNumber = (): number => {
        return this._taskNumber;
    };
}

export default Task;
